export const GET_NEWSLIST = 'GET_NEWSLIST'

export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE'

export const RELOAD = 'RELOAD'

export const RETURN = 'RETURN'

export const SHOWSHAREBOX = 'SHOWSHAREBOX'

export const LOGINING = 'LOGINING'

export const LOGOFF = 'LOGOFF'

export const ROUTERCHANGE = 'ROUTERCHANGE'

export const GETUSERDATA = 'GETUSERDATA'

export const PULLDOWNBTN = 'PULLDOWNBTN'

export const CHANGEINTRODUCE = 'CHANGEINTRODUCE'
